---
- name: Install package
  apt: name=monit state=present update_cache=yes cache_valid_time=900
  sudo: yes
  tags: monit

- name: Setup webinterface
  template: src=webinterface.j2 dest=/etc/monit/conf.d/webinterface owner=root group=root
  notify: restart monit
  tags: monit

- name: Add webinterface ACL rules
  group: name={{ item }} state=present
  with_items: monit_webinterface_acl_rules
  when: monit_webinterface_enabled and monit_webinterface_acl_rules is defined

- name: Add RW group
  group: name={{ monit_webinterface_rw_group }} state=present
  when: monit_webinterface_enabled and monit_webinterface_rw_group is defined
  tags: monit

- name: Add R group
  group: name={{ monit_webinterface_r_group }} state=present
  when: monit_webinterface_enabled and monit_webinterface_r_group is defined
  tags: monit

- name: Setup mail alerts
  copy: src=monit_mail dest=/etc/monit/conf.d/mail owner=root group=root
  notify: restart monit
  when: monit_mail_enabled
  tags: monit

- name: Write monitors
  template: src=monitors/{{ item }}.j2 dest=/etc/monit/conf.d/{{ item }} owner=root group=root
  with_items: monit_services
  notify: restart monit
  tags: monit

- name: List monitors
  shell: ls -1 /etc/monit/conf.d
  when: monit_service_delete_unlisted
  register: old_monitors
  tags: monit

- name: Remove unused monitors
  file: path=/etc/monit/conf.d/{{ item }} state=absent
  with_items: old_monitors.stdout_lines
  when: monit_service_delete_unlisted and ( item not in monit_services + ['mail', 'webinterface'] )
  notify: restart monit
  tags: monit
